# Generated by Django 3.2.13 on 2022-11-17 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='following_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
