# Generated by Django 3.2.13 on 2022-11-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='name',
            field=models.CharField(choices=[('인천 SSG 랜더스필드', 'ssg'), ('고척 스카이돔', '키움'), ('서울종합운동장 야구장', 'lg'), ('수원 케이티 위즈 파크', 'kt'), ('광주-기아 챔피언스 필드', '기아'), ('창원 NC 파크', 'nc'), ('대구 삼성 라이온즈 파크', '삼성'), ('사직 야구장', '롯데'), ('서울종합운동장 야구장', '두산'), ('대전 한화생명 이글스파크', '한화')], max_length=15),
        ),
    ]
