# Generated by Django 3.2.13 on 2022-11-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_stadium_name'),
        ('accounts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.team'),
            preserve_default=False,
        ),
    ]
